version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  api:
      image: PROJECT_NAME:latest
      environment:
        CATALINA_OPTS: "-Ddatabase.host=db"
      ports:
        - 8080:8080
      depends_on:
        - db
